name: Deploy

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: Checks 📝
    uses: ./.github/workflows/checks.yml

  deploy:
    name: Deploy 🚀
    needs: [checks]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/prepare
      - run: pnpm run type-check
      - run: pnpm run build
      - run: pnpm run deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
